if (NOT sfml_FOUND)
    include(FetchContent)
    FetchContent_Declare(sfml GIT_REPOSITORY https://github.com/SFML/SFML.git GIT_TAG 2.6.x)
    FetchContent_GetProperties(sfml)
    FetchContent_MakeAvailable(sfml)
    if (NOT sfml_POPULATED)
        set(FETCHCONTENT_QUIET NO)
        FetchContent_Populate(sfml)
        set(BUILD_EXEMPLES OFF CACHE BOOL "" FORCE)
        add_subdirectory(${sfml_SOURCE_DIR} ${sfml_BINARY_DIR})
    endif()
endif()